### ISSUE TITLE
Assertion error.

### ISSUE THREAD

**Issue by chhyunch** [mnets/pymnet#17]
`mnet = MultilayerNetwork(aspects=2) #aspects==dimension`
`mnet[1,2,'a','b','x','y']=1`
`mnet.add_layer('c',1)`
`mnet.add_layer('z', 2)`
`fig=draw(mnet)`

I tried example of multi aspects.
But they said,

Traceback (most recent call last):
  File "D:/TSMM/2.DigitalHumanities/MultilayerNetworksLibrary/multi_aspect2.py", line 14, in <module>
    fig=draw(mnet)
  File "D:\TSMM\2.DigitalHumanities\MultilayerNetworksLibrary\pymnet\visuals\drawcore.py", line 159, in draw
    assert net.aspects==1
AssertionError

**Comment by cloner174** [comment]
Hi,
Be Aware that the draw function can only draw the networks with just and only one aspect:
```css
The network can be any type of multilayer
    network with a single aspect.
```
